Resources:
  Transfers:
     Type: AWS::DynamoDB::Table
     Properties:
        TableName: ${self:custom.tableName}
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        AttributeDefinitions:
          - AttributeName: transfer_id
            AttributeType: S
        KeySchema:
          - AttributeName: transfer_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST